#ifndef CONN_H
#define CONN_H

#include <stdbool.h>
#include "vector.h" // Include the vector header

typedef struct
{
    int fd;           // File descriptor
    bool want_read;   // Application's intention for reading
    bool want_write;  // Application's intention for writing
    bool want_close;  // Application's intention for closing
    Vector *incoming; // Data to be parsed by the application
    Vector *outgoing; // Responses generated by the application
} Conn;

// Function declarations
Conn *conn_create();
void conn_free(Conn *conn);
void conn_add_incoming(Conn *conn, const uint8_t *data, size_t len);
void conn_add_outgoing(Conn *conn, const uint8_t *data, size_t len);
void conn_clear_buffers(Conn *conn);
Conn *handle_accept(int fd);

#endif // CONN_H